### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by shirleyatgithub** [nealsonli/E-Track#1]
Dear Author,
Thanks for sharing the project. I have tried to download the dataset but I cannot access it. I wonder if there is another way to get access.
Looking forward to your reply.
Best,
Shasha

**Comment by nealsonli** [comment]
Hi Shasha,
I ran the setup.sh script provided in the repo today and was able to download the dataset. Please check if there's any firewall or VPN setting that might potentially block the access.
Thanks,
Nealson

**Comment by shirleyatgithub** [comment]
Dear Nealson, I have tried different VPNs but all failed. I wonder if you can upload it on onedrive or somewhere else. 
Thanks for your quick response. 
Best.

**Comment by shirleyatgithub** [comment]
Dear Nealson,
Thanks for the quick response. I tried another VPN and downloaded the data. However, I encountered another two issues when I ran e_track_unet.py and e_track.py. For the training script e_track_unet.py, the issue is as follows, 
Traceback (most recent call last):
  File "e_track_unet.py", line 35, in <module>
    from tensorflow.compiler.mlir.tensorflow.gen_mlir_cbe_lib import all_passes_registration
ModuleNotFoundError: No module named 'tensorflow.compiler.mlir.tensorflow.gen_mlir_cbe_lib'

And for e_track.py, the issue is as follows, 
Total params: 466,562
Trainable params: 466,562
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "e_track.py", line 535, in <module>
    main()
  File "e_track.py", line 530, in main
    target_event_sets, target_event_set_labels = e_track(eye_dataset)
  File "e_track.py", line 357, in e_track
    pol_buf += [data.polarity]
AttributeError: 'Frame' object has no attribute 'polarity'
I install the dependencies according to the requirements.txt. I wonder if you have any idea about these issues.
Best.
